/// <reference path="../io.ts" />
/// <reference path="../PEFile.ts" />
/// <reference path="node.d.ts" />

var sampleBase64 =
    "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //0..80
    "gAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0K" //80..160
    "JAAAAAAAAABQRQAATAEDAMOHl1AAAAAAAAAAAOAAAgELAQgAAAQAAAAGAAAAAAAAPiMAAAAgAAAAQAAA" //160..240
    "AABAAAAgAAAAAgAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAMAQIUAABAAABAAAAAAEAAAEAAA" //240..320
    "AAAAABAAAAAAAAAAAAAAAOQiAABXAAAAAEAAAKACAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAAAAAAA" //320..400
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAA" //400..480
    "CCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAARAMAAAAgAAAABAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNy" //480..560
    "YwAAAKACAAAAQAAAAAQAAAAGAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAACgAA" //560..640
    "AAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAAgIwAAAAAAAEgAAAACAAUAaCAAAHwCAAABAAAA" //640..720
    "AQAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADYAcgEAAHAo" //720..800
    "AwAACgAqHgIoBAAACioAAEJTSkIBAAEAAAAAAAwAAAB2Mi4wLjUwNzI3AAAAAAUAbAAAAOQAAAAjfgAA" //800..880
    "UAEAALgAAAAjU3RyaW5ncwAAAAAIAgAAIAAAACNVUwAoAgAAEAAAACNHVUlEAAAAOAIAAEQAAAAjQmxv" //880..960
    "YgAAAAAAAAACAAABRxQAAAkAAAAA+gEzABYAAAEAAAAEAAAAAgAAAAIAAAAEAAAAAgAAAAEAAAABAAAA" //960..1040
    "AAAKAAEAAAAAAAYALQAmAAYAXwA/AAYAfwA/AAYApAAmAAAAAAABAAAAAAABAAEAAAAQABUAAAAFAAEA" //1040..1120
    "AQBQIAAAAACRADQACgABAF4gAAAAAIYYOQAOAAEAEQA5ABIAGQA5AA4AIQCsABcACQA5AA4ALgALABwA" //1120..1200
    "LgATACUABIAAAAAAAAAAAAAAAAAAAAAAnQAAAAIAAAAAAAAAAAAAAAEAHQAAAAAAAAAAAAA8TW9kdWxl" //1200..1280
    "PgBzYW1wbGUuZXhlAFByb2dyYW0AbXNjb3JsaWIAU3lzdGVtAE9iamVjdABNYWluAC5jdG9yAFN5c3Rl" //1280..1360
    "bS5SdW50aW1lLkNvbXBpbGVyU2VydmljZXMAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0dHJpYnV0ZQBS" //1360..1440
    "dW50aW1lQ29tcGF0aWJpbGl0eUF0dHJpYnV0ZQBzYW1wbGUAQ29uc29sZQBXcml0ZUxpbmUAAAAAG0gA" //1440..1520
    "ZQBsAGwAbwAsACAAVwBvAHIAbABkACEAAAAAAJLHnA1ayhNJnnaPGHK8wicACLd6XFYZNOCJAwAAAQMg" //1520..1600
    "AAEEIAEBCAQAAQEOCAEACAAAAAAAHgEAAQBUAhZXcmFwTm9uRXhjZXB0aW9uVGhyb3dzAQwjAAAAAAAA" //1600..1680
    "AAAAAC4jAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIwAAAAAAAAAAAAAAAAAAAAAAAAAAX0NvckV4" //1680..1760
    "ZU1haW4AbXNjb3JlZS5kbGwAAAAAAP8lACBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //1760..1840
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //1840..1920
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //1920..2000
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABABAAAAAYAACA" //2000..2080
    "AAAAAAAAAAAAAAAAAAABAAEAAAAwAACAAAAAAAAAAAAAAAAAAAABAAAAAABIAAAAWEAAAEQCAAAAAAAA" //2080..2160
    "AAAAAEQCNAAAAFYAUwBfAFYARQBSAFMASQBPAE4AXwBJAE4ARgBPAAAAAAC9BO/+AAABAAAAAAAAAAAA" //2160..2240
    "AAAAAAAAAAA/AAAAAAAAAAQAAAABAAAAAAAAAAAAAAAAAAAARAAAAAEAVgBhAHIARgBpAGwAZQBJAG4A" //2240..2320
    "ZgBvAAAAAAAkAAQAAABUAHIAYQBuAHMAbABhAHQAaQBvAG4AAAAAAAAAsASkAQAAAQBTAHQAcgBpAG4A" //2320..2400
    "ZwBGAGkAbABlAEkAbgBmAG8AAACAAQAAAQAwADAAMAAwADAANABiADAAAAAsAAIAAQBGAGkAbABlAEQA" //2400..2480
    "ZQBzAGMAcgBpAHAAdABpAG8AbgAAAAAAIAAAADAACAABAEYAaQBsAGUAVgBlAHIAcwBpAG8AbgAAAAAA" //2480..2560
    "MAAuADAALgAwAC4AMAAAADgACwABAEkAbgB0AGUAcgBuAGEAbABOAGEAbQBlAAAAcwBhAG0AcABsAGUA" //2560..2640
    "LgBlAHgAZQAAAAAAKAACAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAIAAAAEAACwABAE8A" //2640..2720
    "cgBpAGcAaQBuAGEAbABGAGkAbABlAG4AYQBtAGUAAABzAGEAbQBwAGwAZQAuAGUAeABlAAAAAAA0AAgA" //2720..2800
    "AQBQAHIAbwBkAHUAYwB0AFYAZQByAHMAaQBvAG4AAAAwAC4AMAAuADAALgAwAAAAOAAIAAEAQQBzAHMA" //2800..2880
    "ZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADAALgAwAC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAA" //2880..2960
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //2960..3040
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //3040..3120
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //3120..3200
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //3200..3280
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //3280..3360
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAMAAAAQDMAAAAAAAAAAAAA" //3360..3440
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //3440..3520
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //3520..3600
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //3600..3680
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //3680..3760
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //3760..3840
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //3840..3920
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //3920..4000
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" //4000..4080
    "AAAAAAAAAAAAAAAA"; //4080..4096

declare var require: (moduleName: string) => any;
var fs = require("fs");

fs.readFile("sample.exe", function (err, fd) {
    if (err)
        throw new Error("Failed to read the sample binary " + err + ".");

    var reader = new io.BufferBinaryReader(fd);

    var peFile = new PEFile();
    peFile.read(reader);

    console.log(peFile);
});